server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boon?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: score

mybatis:
  mapper-locations: classpath:mapper/*.xml

 #下面配置服务的Eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://boon:123456@127.0.0.1:9713/eureka

