server:
  port: 8087
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: shopping-admin
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    timeout: 1800000
  mvc:
    servlet:
      load-on-startup: 1

# 服务注册中心的配置
eureka:
  client:
    service-url:
      defaultZone: http://boon:123456@127.0.0.1:9713/eureka

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# fastDFS的配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    -39.108.98.95:22122

# token的过期时间，单位是秒，这里设置为30分钟
token:
  expire:
    seconds: 30





