server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boon?characterEncoding=utf-8
    username: root
    password: root
  application:
    name: reward-and-punishment

mybatis:
  mapper-locations: classpath:mapper/*.xml

  # 服务注册的配置
eureka:
  client:
    service-url:
      defaultZone: http://boon:123456@127.0.0.1:9713/eureka
